CREATE_PARKING_LOT = 'Create_parking_lot'
PARK_CAR = 'Park'
CAR_EXIT = 'Leave'
GET_SLOTS_HAVING_CAR_OF_DRIVER_AGE = 'Slot_numbers_for_driver_of_age'
GET_REGISTRATION_NUMBERS_HAVING_DRIVER_AGE = 'Vehicle_registration_number_for_driver_of_age'
SEARCH_SLOT_BY_REGISTRATION_NUMBER = 'Slot_number_for_car_with_number'
EXIT_UI = 'exit'